### ISSUE TITLE
[Bug] Forum -> Clicking to join Discord does not work

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#1]
![grafik](https://user-images.githubusercontent.com/36358673/187954413-5e05a550-e360-4b8b-8e8b-14fb17d6edb0.png)

Probably just not set up yet, though i set it here as a bug for to do.

**Comment by Whitescan** [comment]
The forum is work in progress. Currently only the applications are accessable for the public.
