### ISSUE TITLE
[Hardcore] Villager spawnen naturell

### ISSUE THREAD

**Issue by Mind0fBenni** [EndurionNetwork/Endurion#10]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hadcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
30.07.2021 um 15.35 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** 
1.17.1 Java

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni
**Beschreibe den Fehler möglichst genau.**
Es gibt Villiger ob wohl es keine geben sollte.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Es sollte keine williger geben.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Wie es scheint wird das SpawnEvent der Villager nur ausgeführt, wenn sie vermehrt werden.
Somit gibt es zum jetztigen Zeitpunkt keine Möglichkeit sie zu entfernen.
