### ISSUE TITLE
[CITYBUILD] Bedrock durch Bug bekommen

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#101]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Citybuild

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
20:10

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Forge 1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kachiofen + JateNR8

**Beschreibe den Fehler möglichst genau.**
JateNR8 hat durch Zufall einen Fehler gefunden durch den man mithilfe von PVP-Teleportunterdrückung /p h und /p music bedrock und Schallplatten bekommen kann.

Ich habe sichergestellt dass Jate kein Bedrock mehr besitzt und habe die Anweisung gegeben es nicht weiter zu sagen.

Big_Ben hat mich nur geschlagen damit ich ein Video davon machen kann da Jate direkt danach offline gegangen war. (Big Ben weis nichts von dem Bug)

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Naja kein Bedrock

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Arena' Vermutlich auch wo anders möglich
2. Werde von einem Spieler geschlagen - > Combatlog (Habe mit Levin auch ausprobiert hat jedoch nicht funktioniert da man anscheinend von einem Spieler geschlagen worden sein muss) 
3. Nutze Befehl '/p h' und dann '/p music'
4. Dann  'Bedrock / Schallplatten' entnehmen

**Screenshots & andere Anlagen*

https://user-images.githubusercontent.com/87825743/143720258-c4e6e57b-6c3f-492a-9c57-73f237ff1b2e.mp4

*

**Comment by Whitescan** [comment]
Leider ein PlotSquared Fehler. Müssen wir an die Entwickler dort weiterleiten.

**Comment by PalmTamino** [comment]
Kann den Fehler leider nicht reproduzieren. Auf Arena bin ich noch nichmal in einem Plot, und auf anderen geht der Bedrock sofort weg.
