### ISSUE TITLE
[Citybuild] Armor Stands werden nicht von Gravity beeinflusst 

### ISSUE THREAD

**Issue by Anelim101** [EndurionNetwork/Endurion#106]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Citybuild Plot von CommanderTaha27 (-3;-7)

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
20.12.2021 19.53 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Anelim101

**Beschreibe den Fehler möglichst genau.**
CommanderTaha27 hat einen Armor Stand auf einem Stein-Block platziert und diesen dann abgebaut, aber der Armor Stand blieb in der Luft stehen, dies fiel ihm auf, weil er zwei Armor Stands ineinander stellen wollte. Daraufhin hat er einen Support in Minecraft angefordert.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Das der Armor Stand runterfällt, wenn man den Block darunter abbaut. 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Citybuild (Plot -3;-7'
2. Baue einen Block und platziere einen Armor Stand darauf
3. Baue den Block unter dem Armor Stand ab
4. Siehe Fehler 'Armor Stand bleibt in der Luft stehen'

**Screenshots & andere Anlagen**
![unknown](https://user-images.githubusercontent.com/96445227/146828067-1aa0b3a1-9e85-4a7e-b469-d52382ef404c.png)
![unknown](https://user-images.githubusercontent.com/96445227/146828084-88ecf500-df36-4065-833e-8a257b515e32.png)

**Comment by Anelim101** [comment]
Die Angehangen Fotos entstanden auf meinem Plot in Citybuild

**Comment by PalmTamino** [comment]
Hallo, ist der Fehler nur auf dem Plot von Commander Taha?

**Comment by Whitescan** [comment]
PlotSquared behandelt Armorstands mit voller Absicht als Block. Finde das auch gut so. 
Armorstand Stacking ist sowieso verboten aus Lag-Gründen.
