### ISSUE TITLE
[Hardcore] Mobs töten bringen keine EXP Punkte

### ISSUE THREAD

**Issue by Mind0fBenni** [EndurionNetwork/Endurion#11]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hadcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
30.07.2021 um 15.37 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1 Java 

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Wenn ich z.B eine zombi töte bekomme ich kein XP

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
ich sollte XP bekommen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Ein Fehler in der Rechnung führte zu 0 Ergebnissen. Dies wurde behoben und wird mit dem nächsten Update auf dem Server aktiv.
