### ISSUE TITLE
[OneBlock] Villager despawnen wieder

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#110]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
OneBlock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
22:30, 26.02.2022

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.18.1 - optifine

**Nenne uns bitte deinen Minecraft Benutzernamen**
bei instixx1 aufgetreten

**Beschreibe den Fehler möglichst genau.**
Villager, mit denen bereits viel gehandelt wurde, sind despawnt während der Spieler bei besuch auf der Insel eines anderen Spielers war. Die Villager befanden sich dabei auf slabs (eichenholtz), warscheinlich besteht da ein zusammenhang da bei mir persöhnlich das nicht aufgetreten ist wo der villager auf einem ganzem Block stand.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
----

**Schritte um den Fehler zu reproduzieren** -----
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**
![2022-02-26_22 51 09](https://user-images.githubusercontent.com/87825743/155860266-0488cd26-1747-45d4-b492-4d770fbd512d.png)

**Comment by Whitescan** [comment]
Es gibt nur eine Möglichkeit wie sie despawnen. Und zwar wenn zu viele Entities in einem Chunk gecroweded sind. 
Wenn also ein Villager verschwindet, sollte der Spieler den Support aufsuchen. 
In den meisten Fällen wurde der Villager irgendwie getötet.
