### ISSUE TITLE
[Oneblock] Enderkisten gehen nicht

### ISSUE THREAD

**Issue by TxbiTobi** [EndurionNetwork/Endurion#112]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
27.02.2022, 14:20 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java - 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Daddy_Jonas001

**Beschreibe den Fehler möglichst genau.**
Beim öffnen einer EC kommt eine Fehlermeldung

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Keine Fehlermeldung, EC sollte sich normal öffnen lassen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Oneblock
2. Nutze Enderchest
3. Fehlermeldung

**Screenshots & andere Anlagen**
https://cdn.discordapp.com/attachments/947484100325933056/947484274146312263/unknown.png

**Comment by Whitescan** [comment]
Enderchests sind auf OneBlock nur für Premium Spieler um Item duplikation durch Insel Reset zu vermeiden.
