### ISSUE TITLE
[Oneblock] Blöcke ausserhalb der Border

### ISSUE THREAD

**Issue by TxbiTobi** [EndurionNetwork/Endurion#115]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
01.03.2022, 9:30 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java, 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
InsideJeff

**Beschreibe den Fehler möglichst genau.**
Man kann mit einem Piston Blöcke aus der Border schieben. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Es sollte nicht möglich sein.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Oneblock
2. Platziere Piston und Block
3. Aktiviere Piston
4. Block ist ausserhalb der Border

**Screenshots & andere Anlagen**
![](https://cdn.discordapp.com/attachments/948009075722039297/948136986827456522/unknown.png)

**Comment by PalmTamino** [comment]
Behoben. Man kann mit Kolben nun kein Blöcke mehr außerhalb der Border bringen.
