### ISSUE TITLE
[Survival] Man kann nur maximal 50 Chunks claimen

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#116]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Survival

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Am 02.03.2022 12Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Vanilla 1.181

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Es heißt wenn man auf Survival spielt bekommt mal immer mehr chunks zum claimen.  Das ist aber nicht der fall. Ab 50 Chunks hört das komplett auf und man kann nichts mehr claimen. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte eigentlich mehr claimen können (Mehr als 50)

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Survival'
2. Nutze Befehl '1: /land create [Name] dann mache /claim.'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Könnte gefixt sein, ist auch egal da Survival nicht mehr online ist.
