### ISSUE TITLE
OneBlock [/top]

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#117]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
OneBlock 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
21.18 am 09.03.21

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Minecraft java 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
MedusaEmu47

**Beschreibe den Fehler möglichst genau.**
Wenn man z.B in der Lobby von OneBlock ist oder in der arena (auf CB glaube ist das auch so) und man als MVP /top eingibt kommt man auf die barrias . 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Eigenlich sollte man nicht auf das "Dach" kommen.
**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '/oneblock'
2. Nutze Befehl '/tp'
3. Klicke auf '....'
4. Siehe Fehler 'Wie du auf dem dach (barrias  bist.)'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Fixed von @Blu3Crystal
