### ISSUE TITLE
Moderatoren sehen andere Moderatoren nicht im Vanish

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#118]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Alle

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
12.03.2022 01:27 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Fabric 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Wenn ich z.B. auf OneBlock im Vanish bin. kann ich von anderen Moderatoren nicht gesehen werden. 
(Andersherum das selbe.) 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Ich sollte meine Moderation Kollegen im Vanish sehen. 

**Schritte um den Fehler zu reproduzieren**
1. Nutze Befehl /vanish
2. Siehe Fehler...

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Fixed.
