### ISSUE TITLE
[Global] /join

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#119]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Den Fehler findet man auf jedem Server.

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Am 07.04.22 um 21.40.23 Uhr  

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Ich nutze die 1.18.1  fabric API.

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Das ist ganz einfach. 
/join <User> geht nicht mehr.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Wenn ich den Befehl ausführe sollt ich mich mit dem Sub Server des Spielers verbinden. 
Passiert aber nicht. 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'z.B Lobby'
2. Nutze Befehl '/join <User>'
3. Klicke auf '....'
4. Siehe Fehler 'Fehler! Das ist nicht der befehl den du suchst...'

**Screenshots & andere Anlagen**

**Comment by PalmTamino** [comment]
Hmm, geht bei mir. Könnte ich einen Screenshot sehen? @MindOfBenni

**Comment by Whitescan** [comment]
Fixed. Permission hat gefehlt. Wieso ist unklar. Vermutlich eine Änderung in der Vererbung.
