### ISSUE TITLE
[Bungee] Man kann sich selbst reporten

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#123]
![grafik](https://user-images.githubusercontent.com/36358673/162582971-cce4e703-d5ff-407c-b184-fe075c3f2bbe.png)

**Comment by PalmTamino** [comment]
Eigentlich sollte folgendes kommen: 
![grafik](https://user-images.githubusercontent.com/36358673/162583012-82ea40f5-7290-42e1-ab0b-0fa9a2a8ad50.png)

**Comment by Whitescan** [comment]
Wieso sollte man sich nicht selbst für Regelverstoße melden können?
Du kannst dich bei der Polizei schließlich auch selbst anzeigen. 
Kein Fehler. Gilt als Geständnis und würde milder bestraft werden.
