### ISSUE TITLE
[Bungee] /lastseen zeigt Leute im Vanish, ob sie da sind oder nicht

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#124]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
-> Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
-> irrelevant 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
-> irrelevant 

**Nenne uns bitte deinen Minecraft Benutzernamen**
-> irrelevant 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
-> Auf "offline" anzeigen lassen
    -> https://prnt.sc/Pc4RtEG3T7dD

**Comment by Whitescan** [comment]
Dies ist kein Fehler. Dem Spieler bleibt die genaue Position des Moderators nach wie vor verborgen.
