### ISSUE TITLE
[Global] Server schmiert beim Warn ab

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#125]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
12.04.2022 - ca. 18 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
irrelevant 

**Nenne uns bitte deinen Minecraft Benutzernamen**
irrelevant 

**Beschreibe den Fehler möglichst genau.**
Wenn man jemanden verwarnt, schmiert das ganze Netzwerk ab

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Der Server sollte dableiben und der Spieler bestraft werden.

**Comment by Whitescan** [comment]
Fixed.
