### ISSUE TITLE
[Oneblock] /homes nicht setzbar

### ISSUE THREAD

**Issue by MedusaEmu47** [EndurionNetwork/Endurion#126]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
12.04.22 21.29Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
18.1 Normaler Laucher

**Nenne uns bitte deinen Minecraft Benutzernamen**
FiObra

**Beschreibe den Fehler möglichst genau.**
Kann keine Homes setzen Trozdem keiner Aktiven Homes.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**

**Schritte um den Fehler zu reproduzieren**
´Keine Ahnung ^^

**Screenshots & andere Anlagen**
![home](https://user-images.githubusercontent.com/103452227/163041772-b582c92e-cb6b-42a0-9bb4-b98d762b771a.png)
![ka](https://user-images.githubusercontent.com/103452227/163041784-1755d92c-49d5-4858-b6da-6f05aabef6ef.png)
![fehler_meldung](https://user-images.githubusercontent.com/103452227/163041792-b5e55822-95a2-4bcd-a909-b4e448242463.png)

**Comment by Whitescan** [comment]
Hotfixed.
