### ISSUE TITLE
[Oneblock] AngelChest zieht kein Geld vom Konto ab

### ISSUE THREAD

**Issue by Blackdevilvanni** [EndurionNetwork/Endurion#128]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
oneblock1 und 2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
13.04.2022 umd 14:35 uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
vanilla 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Blackdevilvanni

**Beschreibe den Fehler möglichst genau.**
Wenn man sirbt spawnt eine angelchest wenn man 100 oder mehr auf dem konto hat. Das geld beibt aber vorhanden, also es werden keine 100 abgezogen. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
angelchest spawnt, man nimmt sachen und -100 dann. es wird also 100 vom konto abgezogen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu oneblock
2. stirb
3. Klicke auf die angelchest
4. Siehe Fehler im konto

**Screenshots & andere Anlagen**
Ich weis nicht ob es bei anderen usern so ist, es ist aber bei mir so

**Comment by Whitescan** [comment]
Closed for rerelease
