### ISSUE TITLE
[Generell] /top in Arenen und Spawn

### ISSUE THREAD

**Issue by Chainsawwithoil** [EndurionNetwork/Endurion#129]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Badlion

**Nenne uns bitte deinen Minecraft Benutzernamen**
Chainsawwithoil
**Beschreibe den Fehler möglichst genau.**
/top funktioniert immer noch in der Arena und im Spawn

**Wie hätte das Endergebnis stattdessen aussehen sollen?**

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu /spawn und /warp arena
3. Nutze Befehl /top

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Priorität angepasst, da man so in die normale Welt der Arena gelangen kann was zu Datenmüll und inflation führt.

**Comment by Whitescan** [comment]
Fixed by @Blu3Crystal
