### ISSUE TITLE
[Generell] Alle Plugins sind sichtbar

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#13]
Foto --> https://ibb.co/JQSGzFv

Befehl: /bukkit:plugins

**Comment by TaminoPalm** [comment]
Auf Outbreak geht es nur mit /?

**Comment by Whitescan** [comment]
Plugins sind sichtbar, da es für uns keinen Grund gibt diese zu verstecken. Wird also als Vorschlag behandelt und ggf. umgesetzt.

**Comment by Whitescan** [comment]
Zu moderatem Zustand umgesetzt.

**Comment by PalmTamino** [comment]
> 
> 
> Zu moderatem Zustand umgesetzt.

Wollte nur melden, das der "/?" Befehl noch geht

**Comment by PalmTamino** [comment]
Sowie "/help" auf allen nicht "Palmcraft" servern.
