### ISSUE TITLE
Oneblock shulker bug verdoppelt items

### ISSUE THREAD

**Issue by Blackdevilvanni** [EndurionNetwork/Endurion#130]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
14.02.2022 16:22 uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Vanilla 1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Nur_NiclasMc 

**Beschreibe den Fehler möglichst genau.**
Wenn man rechstklick auf schulker macht und control q auf ein item spammt droppt er raus und verdoppelt sich somit.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Das item hätte ganz normal droppen sollen ohne das es sich verdoppelt

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu oneblock
2. Klicke auf schulker mit rechtsklick
4. klicke auf controll und q und damit auf ein item

**Screenshots & andere Anlagen**
--keine vorhanden--

**Comment by Whitescan** [comment]
Dieses Feature hat sich als höchst instabil bewiesen und wurde daher entfernt.
