### ISSUE TITLE
[OneBlock] /spawner get | Schreibfehler 

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#132]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock 1-2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
irrelevant 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
irrelevant 

**Nenne uns bitte deinen Minecraft Benutzernamen**
irrelevant 

**Beschreibe den Fehler möglichst genau.**
Es wird beim Command /spawner get "Du kannst die das nicht leisten." angezeigt.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Da ist das "die" durch "dir" auszutauschen. 

**Schritte um den Fehler zu reproduzieren**
Gehe auf Oneblock
Gib /spawner get ein.
Siehe Fehler

**Screenshots & andere Anlagen**
https://prnt.sc/25PfXvfyQZ1I

**Comment by Whitescan** [comment]
Fixed.
