### ISSUE TITLE
[Oneblock] Rechtschreibfehler

### ISSUE THREAD

**Issue by BigBxn** [EndurionNetwork/Endurion#133]
**Oneblock**

**19.04.2022 10:43**

**18.1 | Badlion**

**ZehMax_28**

**Wenn man einen neuen OB startet oder das End schafft und den ob somit neu startet kommt ,,Viel Gl ck".**

**Es sollte ,,Viel Glück" stehen -> ü vergessen**

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Oneblock'
2. Starte einen neuen Oneblock oder beende die End Phase'

**Screenshots & andere Anlagen**
![grafik](https://user-images.githubusercontent.com/100438742/163966891-edecadb2-1476-4626-ae2a-d445712a790c.png)

**Comment by Whitescan** [comment]
@PalmTamino kannst du mal schauen ob wir das in den Language files von OneBlock gefixt kriegen? Vermute hier fast einen encoding Fehler wegen dem Ü...

**Comment by PalmTamino** [comment]
Ja, das ist in den Language Files. Hatte das Selber mal Angepasst, um die message davor von AOneblock zu OneBlock zu ändern

**Comment by Whitescan** [comment]
Fixed.
