### ISSUE TITLE
[OneBlock] Namtag Glitch

### ISSUE THREAD

**Issue by kingoffiziell** [EndurionNetwork/Endurion#135]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Ob 1 Ob 2 Warscheinlich auch auf alle anderen modis 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
25.04.2022 17.50

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
18.2

**Nenne uns bitte deinen Minecraft Benutzernamen**

**Beschreibe den Fehler möglichst genau.**
Wenn man als Bedrock Spieler ein Nametag benennt, setzt sich dieser zurück und heißt nur "Nametag"

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Bennen und sollte so bleiben 

**Schritte um den Fehler zu reproduzieren**
1. Nutze einen Anvil
2. Bennene diesen z.B. "Pommes"
3. Klicke Enter 
4. Siehe Fehler

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
@PalmTamino hängt das vllt auch mit Triton zusammen?

**Comment by Whitescan** [comment]
Fixed.
