### ISSUE TITLE
[Alle!] Mann kan keine Items aufsammen in der arena!

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#136]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Alle 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
26.04.2022 17.16Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.18.1 fabric 

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Wenn ich jemand in der arena töte Droppen zwar die items man kann sie aber nicht aufsammeln. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte die  Items Aufsammeln könne. 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'egal Hauptsache es gibt eine arena.'
2. Nutze Befehl '/warp arena'
3. Klicke auf '/'
4. Siehe Fehler 'Hey! Sorry, but you can´t pick up items here.'

**Screenshots & andere Anlagen**
https://medal.tv/games/minecraft/clips/j5VUB7Zp2gNr5/d1337k8VfkmJ?invite=cr-MSxjMkMsNDg2NzkyNTMs

(Alle Items in dem Video wurden bereitgestellt. Die JrModeratoren Haben keinen Stuff verloren!)

**Comment by Blu3Crystal** [comment]
Sollte behoben sein - Region auf Allow gesetzt /item pickup & /item drop
