### ISSUE TITLE
End Crystal Bug

### ISSUE THREAD

**Issue by kingoffiziell** [EndurionNetwork/Endurion#137]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
23.06 am 25.04.2022

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.18.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
king_offiziell

**Beschreibe den Fehler möglichst genau.**
Wenn ein End Crystal Explodiert das er kein Schaden an den Blöcken Macht

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Wenn der endcrystal explodiert sollte er blöcke schaden anfügen 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...' Obsidian 
2. Nutze Befehl '....' Platziere ein End Crystal 
3. Klicke auf '....' Links auf den Endcrystal 
4. Siehe Fehler '....' kein Schaden an den blöcken nur schaden an dich 

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Dies ist kein Fehler sondern Vanilla verhalten. Deaktiviere ggf. Explosionensschaden auf deiner Insel mit den /ob settings.
