### ISSUE TITLE
[Allgemein] Nametags Name Encoding Fehler mit ÜÖÄ

### ISSUE THREAD

**Issue by BigBxn** [EndurionNetwork/Endurion#138]
**Auf welchem Server hast du den Fehler gefunden? 
Oneblock**

**Wann hast du den Fehler gefunden? 
12.05.2022 19:19**

**Welche Minecraft Version nutzt du? 
Badlion 1.18.2**

**Nenne uns bitte deinen Minecraft Benutzernamen 
Big_Bxn**

**Beschreibe den Fehler möglichst genau.**
Wenn man einem Mob den Nametag mit dem Buchstaben Ü gibt wird das nicht angezeigt.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Ein Ü hatte angezeigt werden.

**Schritte um den Fehler zu reproduzieren**
1. Mache ein Namensschild mit ü
2. gebe einem Mob das Nametag

**Screenshots & andere Anlagen**
![grafik](https://user-images.githubusercontent.com/100438742/168132774-188a205d-f3df-4efd-a728-649e8ca400df.png)

**Comment by Whitescan** [comment]
@PalmTamino scheint an Triton zu liegen?

**Comment by Whitescan** [comment]
Fixed.
