### ISSUE TITLE
[Survival] Nether Tod lässt einen immer wieder im Nether spawnen

### ISSUE THREAD

**Issue by kingoffiziell** [EndurionNetwork/Endurion#139]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Survival 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Am 14.05.2022 um 16.51 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Badlion 1.18.2

**Nenne uns bitte deinen Minecraft Benutzernamen**
king_offiziell

**Beschreibe den Fehler möglichst genau.**
Wenn man im Nether stirbt , spawant man ganze Zeit an der gleichen Stelle.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte zum Spwan oder zu sein Land teleportiert  werden.

**Schritte um den Fehler zu reproduzieren**
1. Gehe über ein Nehter Portal ins Nehter. 
2.  im Nehter sterben an lava etc 
4.  Man respwant an der gleichen stelle und ist getrappt 

**Screenshots & andere Anlagen**
Vidio kann ich nur per dc schicken

**Comment by Whitescan** [comment]
Vermutlich ein Fehler im Endurion Essentials...

**Comment by Whitescan** [comment]
Fixed.
