### ISSUE TITLE
[Citybuild] Plot Boden

### ISSUE THREAD

**Issue by BigBxn** [EndurionNetwork/Endurion#141]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Citybuild

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
29.05.2022 17:20

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Feather, 1.18.2

**Nenne uns bitte deinen Minecraft Benutzernamen**
Big_Bxn

**Beschreibe den Fehler möglichst genau.**
Der Boden der Plots wurde irgendwie um eins angehoben und jetzt kann man da gebaute Blöcke nicht abbauen und bei neuen Plots ist da schwarzer BEton und stein

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte die Blöcke abbauen können

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf Citybuild
2. Nutze Befehl /p h oder /p v 
3. Baue bei einem Plot bis ganz nach unten

**Screenshots & andere Anlagen**
![grafik](https://user-images.githubusercontent.com/100438742/170877255-e9c4366c-75fa-4124-8381-f860cb2625a1.png)
![grafik](https://user-images.githubusercontent.com/100438742/170877280-092f7c26-d51c-4132-ad9a-28ef254022b2.png)

**Comment by Whitescan** [comment]
Behoben.
