### ISSUE TITLE
Blöcke bug 

### ISSUE THREAD

**Issue by kingoffiziell** [EndurionNetwork/Endurion#142]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Ob1

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Am 29.05.2022 um 18:01

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.18.2 Badlion 

**Nenne uns bitte deinen Minecraft Benutzernamen**
king_offiziell

**Beschreibe den Fehler möglichst genau.**
Wenn man normal Blöcke  abbaut bugen Blöcke weg passiert nicht zu 100% 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Wen ein Block abbaut das man den  Block bekommt und nicht wegbugt.

**Schritte um den Fehler zu reproduzieren**
1. Baue ein Block ab 
2. Es dropt kein Block

**Comment by Whitescan** [comment]
Das kann an allem möglichen liegen. Es ist allerdings kein Fehler in unserer Software.
Könnte durch Latenzen oder Überlastung kommen.
