### ISSUE TITLE
[Globla] Fehlende recht für das Senior Team

### ISSUE THREAD

**Issue by MindOfBenni** [EndurionNetwork/Endurion#144]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Global

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
30.05.2022

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Nicht relevant. 

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Mache rechte gehen nicht.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Die rechte sollten gehen. 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Nicht relevant. '
2. Nutze Befehl 'Unten angegeben.'
3. Klicke auf 'Nicht relevant. '
4. Siehe Fehler 'Befehl kann nicht ausgeführt werden. '

**Screenshots & andere Anlagen**
https://docs.google.com/document/d/11OgTRslPjYJ0gafmSH4yGtmu7ngX9pzhO9fTi2KKTLA/edit

**Comment by Whitescan** [comment]
Falscher Ort.
