### ISSUE TITLE
[Oneblock2] Öfen funktionieren nicht

### ISSUE THREAD

**Issue by MedusaEmu47** [EndurionNetwork/Endurion#146]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
13.06.2022 01:50

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.18.1 

**Nenne uns bitte deinen Minecraft Benutzernamen**
MedusaEmu47 & ByDachs

**Beschreibe den Fehler möglichst genau.**
Items können nicht geschmolzen / gekocht werden. Zuckerohr bleibt in der Luft Schweben. Kakteen wachsen direkt an Blöcken.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Öfen Sollten funktionieren, Zuckerohr sollte herab fallen, kakteen sollten nicht direkt an blöcken wachsen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Oneblock2
2. Nutze Befehl N/A
3. Klicke auf N/A
4. Siehe Fehler : Diese Dinge gehen Nicht

**Screenshots & andere Anlagen**
Nicht Vorhanden.

**Comment by Whitescan** [comment]
Fixed.
