### ISSUE TITLE
[Citybuild] Man kann immer noch nicht auf Höhe 1 abbauen...

### ISSUE THREAD

**Issue by BigBxn** [EndurionNetwork/Endurion#147]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Citybuild

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
16.07.2022 23:20

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.19 Badlion

**Nenne uns bitte deinen Minecraft Benutzernamen**
Big_Bxn

**Beschreibe den Fehler möglichst genau.**
Man kann keine Blöcke auf Höhe 1 abbauen.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Der Block sollte abgebaut werden kömmem

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf Citybuild
2. Gehe auf die Höhe 1
3. Baue einen Block auf Höhe 1 ab
4. Siehe Fehler Block wird nicht abgebaut

**Screenshots & andere Anlagen**

 - Auf bereits generierten Plots:

https://user-images.githubusercontent.com/100438742/179372331-8eae6c71-af7c-4d84-bbb8-b398230546a9.mp4

![grafik](https://user-images.githubusercontent.com/100438742/179372313-45a9a015-7cfb-432f-a0bf-48070402d088.png)

 - Auf neu generierten Plots:
![grafik](https://user-images.githubusercontent.com/100438742/179417114-1b391278-33a1-4aad-9521-223a0e8d3986.png)

**Comment by Whitescan** [comment]
Ich konnte zwar feststellen das unter bestimmten umständen ein Problem besteht, muss aber ehrlich zugeben keine Lösung zu finden.
Könnte mit dem Minecraft Update zusammenhängen das nun unter höhe 0 gebaut werden kann.
Ist eventuell aber auch ein Fehler im Plugin selbst.
Weiß momentan nicht, wie ich das lösen kann. Tut mir sehr Leid.
