### ISSUE TITLE
/find fehler

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#17]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**: Allen

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**: 02.08.2021 - 22 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**: LabyMod 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**: lxvin07

**Beschreibe den Fehler möglichst genau.**: Wenn man /find eingibt kommt eine andere Nachricht als kommen sollte.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**: "Der Spieler %player% ist auf %server%
 

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf denn Server
2. Nutze Befehl '/find <dein name>'
3. Sieh denn fehler

**Screenshots & andere Anlagen**: https://prnt.sc/1ighqar

**Comment by Whitescan** [comment]
Dies war ein Übersetzungsfehler. Der Übersetzer hat den Text falsch verstanden. Der Text wurde korrigiert.
