### ISSUE TITLE
[Generell] Mute blockiert falsche Befehle

### ISSUE THREAD

**Issue by Whitescan** [EndurionNetwork/Endurion#18]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Nicht relevant

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
Sir_MayonesenGolemEsser - Discord

**Beschreibe den Fehler möglichst genau.**
Wenn man einen Mute erhalten hat, kann man keine Shops mehr erstellen.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Shops haben nichts mit dem Chatverhalten zu tun.

**Schritte um den Fehler zu reproduzieren**
1. Gemuted sein
2. Shop erstellen
3. Siehe Fehler

**Screenshots & andere Anlagen**

**Comment by LionDev-tech** [comment]
Hey,
man kann auch wenn man gemuted ist mit dem Befehl "/quickshop create" einen Shop erstellen.
Mfg Lion_King287

**Comment by Whitescan** [comment]
Es ist nicht möglich diesen Fehler zu beheben. 
Der Nutzer der gegen die Regeln verstoßen hat, hat hier einfach Pech gehabt. 
Vielleicht hält er sich dann beim nächsten Mal an die Regeln.
