### ISSUE TITLE
[Oneblock] MobStack funktioniert nicht mehr

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#19]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock 2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
04.08.2021 18 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
fabric 
1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kachiofen

**Beschreibe den Fehler möglichst genau.**
MobStack stackt die Mobs nicht wie üblich was zu Laags führen kann

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OB2'
2. Viele Mobs auf einer stelle
3. Siehe Fehler

**Screenshots & andere Anlagen**
![2021-08-04_18 08 11](https://user-images.githubusercontent.com/87825743/128215692-e2400c7d-8ff6-436e-968c-6b0e2e855c6a.png)

**Comment by Whitescan** [comment]
Fehler wurde mit einem Restart / Update behoben.
