### ISSUE TITLE
[Bug] Message when performing a moderating action is not shown correctly in the Discord under #automod-log

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#2]
![grafik](https://user-images.githubusercontent.com/36358673/188270891-98a6d0b4-85af-419a-9f33-30f665150358.png)

Triton does not seem to work, in addition the chat formatting does not work.

**Comment by PalmTamino** [comment]
Suggestion: Use something like this instead -> 
![grafik](https://user-images.githubusercontent.com/36358673/188271727-f9c3d1ab-c546-42a1-b366-c61e8f7d23a6.png)

**Comment by Whitescan** [comment]
Fixed.
