### ISSUE TITLE
[Oneblock] Schlafnachrichten sind nicht in der Actionbar

### ISSUE THREAD

**Issue by LionDev-tech** [EndurionNetwork/Endurion#20]
Dass wieder auf allen OBs die Schlafnachrichten in der Actionbar angezeigt werden.

**Comment by Whitescan** [comment]
Dies ist kein Vorschlag, sondern ein Fehler.

**Comment by Whitescan** [comment]
Wurde behoben, die Configuration hatte sich durch ein Update zurückgesetzt.
