### ISSUE TITLE
[Survival] -Vorschläge

### ISSUE THREAD

**Issue by Jessi1Pingu** [EndurionNetwork/Endurion#21]
**A**

•	Auktionshaus

**B**

•	Bis zu 3 Jobs gleichzeitig -Survival
👍 59

**E**

•	Entfernung der 25€ bei Land Teleportationen 
👍 34 👎 4
•	Nur eine Enderman für Jeden
👍 5

**H**

•	Höhere spawnrate der Tiere 
👍 40  👎11

**R**

•	Random Teleport 
             - Radom Teleportation zu einem Ort für eine bestimmte Summe an Geld
            👍 28  👎 5

**S**

•	Shop mit Fässern, nicht nur mit Kisten
•	Sichere Angelchest bis sie weg sind
👍 25 👎17
•	Senkung der Landerhaltungskosten auf 10€
            👍 31 👎4
•	Starter Kit 
32 Brot, Stein Tools etc. 
            👍6 👎 1

**Comment by Whitescan** [comment]
Vorschläge teils nicht mehr relevant, teilweise in Hardcore (Survival 2.0) umgesetzt, teils abgelehnt.
