### ISSUE TITLE
[Generell] Server Rang Prefix wird nicht in der Tablist angezeigt

### ISSUE THREAD

**Issue by LionDev-tech** [EndurionNetwork/Endurion#22]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
04.08.2021 22:00

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
Lion_King287

**Beschreibe den Fehler möglichst genau.**
Ein Spieler mit MVP hat auf Hardcore nur im Chat den Prefix aber in der Tablist nicht.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Der Spieler sollte den MVP Prefix in der Tablist haben-

**Schritte um den Fehler zu reproduzieren**
1. Server Rang erwerben
2. Auf den Server gehen
3. Siehe Fehler in der Tablist.
**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Dieses ist ein Anzeigefehler. Es hat mit der Kontext konstallation zu tun.
