### ISSUE TITLE
Fehler mit /ec [Name] für Mods

### ISSUE THREAD

**Issue by Krescher15** [EndurionNetwork/Endurion#23]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore, Outbreak

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Donnerstag, 5 August 15:21

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Minecraft 1.16.5/Fabric (Modded)            [Wurst Client]

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kreescher15

**Beschreibe den Fehler möglichst genau.**
Man kann nicht in Enderchests von anderen Spielern gucken.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte in die Enderchests anderer Spielern schauen können.

**Schritte um den Fehler zu reproduzieren**
1. /ec [Name]

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/88187330/128357355-1e55566a-3e4c-471b-a107-679e3f4beaf0.png)

**Comment by Whitescan** [comment]
Dies ist kein Fehler, das richtige Kommando ist /openender. 
Es ist jedoch geplant das für euch bald angenehmer zu machen.
