### ISSUE TITLE
[Hardcore] Ancient Depris kann nicht mit /smelt geschmolzen werden

### ISSUE THREAD

**Issue by LionDev-tech** [EndurionNetwork/Endurion#24]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
05.08.2021 17:40 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
Lion_King287

**Beschreibe den Fehler möglichst genau.**
Mann kann Anciend Debri nicht mit /smelt schmelzen.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man hätte ein geschmolzen sein müssen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Hardcore
2. Nimm Anciedn Debri in die Hand
3. Nutze Befehl /smelt
4. Siehe Fehler 
**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Das Subsystem wurde ursprünglich für die 1.8.8 programmiert, als es aktualisiert wurde ist dies einfach nicht aufgefallen.
Änderung wird beim nächsten Update aktiv.
