### ISSUE TITLE
Spielerköpfe verschwinden in Hardcore vermehrt 

### ISSUE THREAD

**Issue by Krescher15** [EndurionNetwork/Endurion#25]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Donnerstag, 5. August      18:54

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Minecraft 1.16.5/Fabric (Modded)

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kreescher15

**Beschreibe den Fehler möglichst genau.**
Wenn man in Hardcore durch einen Zombie stirbt, verschwindet der Kopf, da sich denn der Zombie aufsetzt.
Da die Mobs meist schon despawnen aber die Items nicht wenn man ankommt erschwert das sehr das Widerbelebungssystem, deswegen wurde es von mir als Fehler eingestuft.

Eventuell könnte man dies durch Änderungen verbessern.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
-

**Schritte um den Fehler zu reproduzieren**
1. Spieler von Zombie töten lassen
2. Zombie setzt den Kopf auf

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/88187330/128390865-01d55052-f360-4523-ad55-62715fe5630d.png)

**Comment by Whitescan** [comment]
Spielerköpfe können nun nurnoch von anderen Spielern aufgesammelt werden.

Änderung wird mit dem nächsten Update aktiv.
