### ISSUE TITLE
User - Länder und Chunkreduzierung in Hardcore

### ISSUE THREAD

**Issue by Blu3Crystal** [EndurionNetwork/Endurion#28]
Aufgrund der derzeit nicht verfügbaren Plugins Quest/Job wurden die Länder frei zugänglich gemacht (Ohne Geld)
Ein User kann derzeit 10 Länder claimen und 150 Chunks. (Wenn ich richtig gelesen habe)

1. Frage: 150 Chunks auf jeden Land oder zusammen?
2. Eventuell reduzieren da es ja nun kostenlos ist und unsere Welt auch begrenzt ist

**Comment by Whitescan** [comment]
Abgelehnt, da die Spielwelt nach Bedarf vergrößert werden kann. Außerdem gibt es ein Claim Limit das verhindert das alles einem Spieler gehört. Zusätzlich werden Claims nach 90 Tagen Inaktivität an ein Mitspieler weitergegeben oder wenn keiner vorhanden aufgelöst.
