### ISSUE TITLE
[OneBlock] Insel gesperrt und keine Teleportation per Mod möglich

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#29]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** OneBlock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 06.08.2021 - 15:30 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** LabyMod 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.**  Wenn eine Insel gesperrt ist, können wir Moderatoren uns nicht zum Spieler Teleportieren.

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Moderatoren sollten sich eigentlich Teleportieren können

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OneBlock'
2. Nutze Befehl '/ob settings'
3. Klicke auf 'Insel Sperren'
4. Versuche über ein anderen Account dich zu dir zu Teleportieren
5. Siehe Fehler

**Screenshots & andere Anlagen** https://prnt.sc/1jvg153

**Comment by Whitescan** [comment]
Es scheint an einer Permission in der Moderationstrack zu mangeln.

**Comment by SirBoto** [comment]
Kein Fehler! Ab dem Moderator-Rang, mit welchem man ja erst anfängt die Spieler zu überwachen, kann man dies umgehen.

**Comment by lxvin2** [comment]
Es ist ja nicht nur zum Überwachen da. 
Es dient ja auch dazu Spieler zu helfen wenn sie bei ihren Insel ein Problem haben.

**Comment by SirBoto** [comment]
In dem Fall kann man ja dem Spieler schrieben, dass er dich entlocken/entbannen soll von der Insel. Und wenn er dir dann nicht vertraut, hat er halt Pech und ihm kann nicht geholfen werden. Denn wenn er uns da nicht vertraut, wieso sollte er unserer Hilfe vertrauen.
