### ISSUE TITLE
[OneBlock] Hit durch Block

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#30]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** OneBlock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 06.08.2021 - 15.35 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** LabyMod 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07 (gemeldet von EinGamerClient)

**Beschreibe den Fehler möglichst genau.** Wenn eine Spinne Spawn und diese unter ein Block klettert, bekommt der Spieler oben drauf Schaden.

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Der Spieler hätte kein Schaden bekommen sollen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OneBlock'
2. Versuche eine Spinne aus denn OneBlock zu bekommen
3. Schlage diese runter
4. Siehe Fehler (Besser zu sehen in Video)
 
**Screenshots & andere Anlagen** https://imgur.com/a/jrP508e

**Comment by Whitescan** [comment]
Sieht mir nach einem Vanilla Bug aus, Könnte aber auch an der Serversoftware selbst liegen. Ist also keine Garantie das wir dort etwas gegen machen können.
