### ISSUE TITLE
[Generall] VIP Rang Verbesserung

### ISSUE THREAD

**Issue by Krescher15** [EndurionNetwork/Endurion#31]
Das der Rang VIP die Möglichkeit bekommt /smelt nutzen zu können.

**Comment by Whitescan** [comment]
@Krescher15 Bitte gib an welchen Spielmodus dein Vorschlag betrifft.

**Comment by Krescher15** [comment]
Bei allen, ansonsten halt nur bei Hardcore.

**Comment by PalmTamino** [comment]
> Das der Rang VIP die Möglichkeit bekommt /smelt nutzen zu können.

Sehe ich als Rückschritt an, wir sollten nicht zu stark p2w dinge einbauen. Da es ja ein Vorschlag ist, gebe ich meine Meinung einfach mal dazu. Man sollte meiner Meinung eher auf Cosmetics setzen, es gibt genug Spieler denen das reicht, und auch welche die es nicht so toll fänden wenn mehr p2w eingebaut werden würde. Zudem achtet Mojang seit der 1.17 stärker denn je darauf welcher Server p2w ist, und blockt diese. Das Risiko sollten wir meiner Meinung nach nicht eingehen.

**Comment by Whitescan** [comment]
Abgelehnt. Diese Rechte sind einem höheren Premium Status zugestanden.
