### ISSUE TITLE
[Discord]-Vorschläge

### ISSUE THREAD

**Issue by Jessi1Pingu** [EndurionNetwork/Endurion#32]
**B**

•	Discord Banner
👍12 👎 2 

**D**

•	Discord Server Booster erhalten Vip Rang oder ähnliches solange ihr Boost läuft

**P**

•	Profil erstellen wie auf Palmcraft
•	Profil erstellen 
Beispiel: Alter,  Java oder Bedrock, Junge oder Mädchen usw.

**Comment by Whitescan** [comment]
1. Discord Banner halte ich für störend, da es doch recht viel Bildfläche in der Channel View einnimt. Die ist sowieso schon so unhandlich in Discord.
2. Der VIP Rang unterstützt direkt die Endurion Entwicklung. Ein Boost bringt dem Netzwerk keinen direkten Nutzen sondern nur den Nutzern die auf unserem Discord sind. Dies ist rein freiwillig und somit sehe ich keine Notwendigkeit für einen In-Game Rang.
3. Ein Profil zu erstellen halte ich zwar für Lustig und interessant, aber gibt wieder viel potentzial für Trolling auf dem Discord.

**Comment by Whitescan** [comment]
1. Die Banner Funktion scheint sich geändert zu haben. Angenommen.
2. - / -
3. Endgültig abgelehnt, es gibt von Discord die "Über mich" Seite bzw eine Bio. Das muss reichen.
