### ISSUE TITLE
[Boxed]-Vorschläge

### ISSUE THREAD

**Issue by Jessi1Pingu** [EndurionNetwork/Endurion#33]
1. Das man z.B. Boxed2 auf Boxed1 verschieben kann 👍 7
2. Anzeige wie weit die Achievements sind und welche fertig sind per Command 
3. Haustiere traden
4. Sichere Angelchest bis sie weg sind 👍 25 👎17
5. /Skip night für eine Abstimmung ob die Nacht übersprungen werden soll 👍2 👎 6
6. Welten Reset alle 2 Wochen aufgrund von Erzmangel

**Comment by Whitescan** [comment]
1. Halte ich für unnötig da es ja von Minecraft schon die Achivemtn Overview gibt. Der Chat kann die Menge an Nachrichten sowieso nicht darstellen.
2. Das halte ich für eine lustige Sache, aber es gibt definitiv wichtigere Dinge zu bearbeiten als Haustiere.
3. Angelchests sind absichtlich nicht unendlich gesichert.
4. Es gibt bereits ein BetterSleep System. Nur eben ohne Kommando was Nutzer dazu bewegt ein Feature (das Schlafen) wirklich zu nutzen. Dies werden wir nicht zerstören. Bewertungen zeigen die meisten sind ebenfalls gegen einen Befehl.
5. Die Box kann verschoben werden, kein Grund die Bauwerke der Spieler zu löschen.

**Comment by Whitescan** [comment]
1. -/-
2. -/-
3. -/-
4. -/-
5. -/-
6. Abgelehnt, würde Spielstände zurücksetzen.
