### ISSUE TITLE
[Generell] Vorschläge

### ISSUE THREAD

**Issue by Jessi1Pingu** [EndurionNetwork/Endurion#35]
1. Costmetics Veränderung:
VIP: Türkise Partikel ähnelnd einen Schweif
MVP: Goldenen Flammen die Wie eine DNA um den Skin herumfliegen (Bearbeitet)
Elite: eine Gold-Lila Krone auf dem Kopf

2. der Command bei Oneblock friendly statt /oneblock3  -> /oneblockfriendly 👍 8 👎 2
3. Free Cosmetics für Spieler
4. Clans erstellen 👍8
5. /friend command 👍4
6. Ingame Ränge kaufen mit Ingame Währung  (z.B. Anfänger, Fortgeschritten…etc.) mehr Homes dadurch bekommen 👍1 👎 1
7. /nick für Mods 👍 13
8. Änderung der Slots für Dynamik 👍4 👎 8
9. Das man einen Shop machen kann wo 2 Leute verkaufen können und das Geld geteilt wird wen wer was kauft👍9
10. Teammitglieder weiße Schrift im Chat für bessere Erkennung
11. TikTok Video aufm Palmcraft das sich die IP geändert hat. 👍 5
12. Anzeige in der Tablist wie viele Nutzer online sind / wer gerade auf deiner Insel/Grundstück ist
13. Wenn ein User den Server betritt man sieht wer das ist

**Comment by Whitescan** [comment]
1. Cosmetics werden derzeit nicht bearbeitet und auch nicht offiziell angeboten. Somit kann den Nutzern gar nicht klar sein, was dort geplant ist.
2. Gerne können beide Server Aliase eingebaut werden.
3. Siehe Punkt 1.
4. Ein Globales Clansystem ist nicht geplant, hingegen kann man Gilden / Fraktionen und Clans auf z.B. Hardcore gründen.
5. Ein Freunde System ist eine sinnvolle Erweiterung. Angenommen.
6. Die Ränge sind dazu gedacht den Server finanziell am Leben zu halten und bleiben somit Kostenpflichtige Inhalte.
7. Ein Disguise System (Skin Change + Nickname) ist für alle aufsehenerregenen Spieler geplant.
8. Wurde bereits angepasst.
9. Keine einfache Aufgabe. Als nächstes hat man 3 Spieler und man soll teilen. Schwups geschehen Rundungsfehler und man kann sich Geld erschummeln. Aber ein Gedanken Wert. Angenommen.
10. Alle Teammitglieder können ihre Chatformat frei anpassen.
11. Ein TikTok wurde mehrfach veröffentlicht zu diesem Thema.
12. Abgelehnt, die Tabliste agiert global und soll nur Basis Informationen anzeigen.
13. Abgelehnt, sorgt für Spam da manche Spieler öfter sich neu verbinden.

**Comment by Whitescan** [comment]
1. -/-
2. Umgesetzt
3. Teils gleich, andereits soll Content erspielt nicht verschenkt werden.
4. Wird per Server umgesetzt
5. Umgesetz
6. -/-
7. -/-
8. Umgesetzt
9. -/-
10. -/-
11. Umgesetzt
12. Zum Teil angenommen. Es wird ein Globaler Playercount eingesetzt @Whitescan 
13. Teils gleich, man wird künftig über den Beitritt und das Verlassen eines Freundes informiert.
