### ISSUE TITLE
[Oneblock] Items verschwinden

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#36]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
OB1

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
17:30 (vermutlich schon älter)

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.5 Labymod

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kachiofen

**Beschreibe den Fehler möglichst genau.**
Items die auf den Boden geworfen werden, verschwinden/despawnen schon nach wenigen Sekunden.
Es ist anscheinen nur Cobblestone betroffen aber es wurde schon der Verlust von 2 Nethritepickaxes und einer Netheriteaxe

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Items liegen am Boden

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OB1'
2. Items Droppen
3. Siehe Fehler

**Screenshots & andere Anlagen**
Das Video ist leider zu groß für einen Upload, also mit OneDrive
https://1drv.ms/v/s!ApibSGwlK8oEg2I9VLFVQ7WB61nh?e=qsK6Rb

**Comment by Whitescan** [comment]
Cobblestone und Netherrack despawnt nach einer Minute. Alle anderen Items nach 5. Optimiertes Vanilla verhalten.
