### ISSUE TITLE
[OneBlock] NPC für Auktionshaus geht nicht

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#37]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**  Nur OneBlock-3

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 11.08.2021 - 15 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** LabyMod 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.** Der Auktionshaus NPC auf OneBlock-3 geht nicht. Der Befehl /ah geht dennoch

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OneBlock-3'
2. Gehe zum NPC
3. Klicke auf denn NPC
4. Siehe Fehler

**Comment by Whitescan** [comment]
Es war ein falscher Befehl in der Config eingetragen.
