### ISSUE TITLE
[Oneblock] Gepanzerte Elytra kann nicht enchanted werden

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#38]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
OB2

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
11.80.2021 17.10

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.5 Labymod

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kachiofen

**Beschreibe den Fehler möglichst genau.**
Gepanzerte Elytrad können nicht verzaubert werden.
Bzw. nicht in einem Amboss mit einem Buch verbunden werden.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'OB2'
2. Benutze 'Amboss'
3. Siehe Fehler

**Screenshots & andere Anlagen**
![2021-08-11_17 10 27](https://user-images.githubusercontent.com/87825743/129056308-330dc915-a245-464c-9151-f92cee6e1343.png)
![2021-08-11_17 10 30](https://user-images.githubusercontent.com/87825743/129056337-eefa17bf-c5b1-4023-9b70-6b6648b2d6ea.png)

**Comment by PalmTamino** [comment]
Hey, ich habe das mal getestet, und tatsächlich ist es ein Fehler. Da ich zu wenig Rechte habe, füge ich jetzt @Whitescan hinzu.

**Comment by Whitescan** [comment]
"Fixed" in Häkchen da die Gepanzenten Elytren aus Balancing Gründen entfernt wurden.
