### ISSUE TITLE
[Lobby] Skin wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by Whitescan** [EndurionNetwork/Endurion#40]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Lobby

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
-

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Whitescan

**Beschreibe den Fehler möglichst genau.**
Skin wird nicht richtig angezeigt.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
NiAnLaster's Skin sollte erscheinen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu den Lobby NPC's
2. Siehe Fehler

**Screenshots & andere Anlagen**
https://prnt.sc/1nqojr3

**Comment by Blu3Crystal** [comment]
Wurde behoben. Habe auch Krescher seinen ingame Namen angepasst, da er ja einen neuen Acoount hat.

**Comment by Blu3Crystal** [comment]
Skin wurde nicht geladen.
Behoben mit den Neuladen des Skins des Users.
