### ISSUE TITLE
[GLOBAL] Sign-System

### ISSUE THREAD

**Issue by LionDev-tech** [EndurionNetwork/Endurion#41]
Dass z.B. dieses [Signsystem](https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-rhsignitem-sign-your-items-1-12-2-1-17-1.66509/updates) (Es hat sogar die Möglichkeit den LP Prefix anzuzeigen) auf allen Server ist, damit man ab einem bestimmten Rang z.B. VIP Items signieren kann.

**Comment by Whitescan** [comment]
Abgelehnt. Ist zum Teil vorhanden und zu anderen Teilen nicht erwünscht.
