### ISSUE TITLE
[HARDCORE] Wenn man einer Fraktion beitreten möchte steht da "/Fraktion accept" obwohl man "/guilde accept" eingeben muss

### ISSUE THREAD

**Issue by einsCoco** [EndurionNetwork/Endurion#42]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**

**Nenne uns bitte deinen Minecraft Benutzernamen**

**Beschreibe den Fehler möglichst genau.**

**Wie hätte das Endergebnis stattdessen aussehen sollen?**

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Man **muss** es nicht, der Befehl hat mehrere Aliase. /faction, /guilde, /fraktion und /clan. Alle sollten funktionieren.
