### ISSUE TITLE
[Generell] Bei MSG's werden die Server immer als hidden angezeigt

### ISSUE THREAD

**Issue by Whitescan** [EndurionNetwork/Endurion#43]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
-

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1 Java

**Nenne uns bitte deinen Minecraft Benutzernamen**
Whitescan

**Beschreibe den Fehler möglichst genau.**
Wenn man MSGs versendet werden die Server immer als hidden angezeigt.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Der Server sollte angezeigt werden wenn der Spieler Zugriff auf diesen hat.

**Schritte um den Fehler zu reproduzieren**
1. MSG versenden
2. Siehe Fehler im Chat

**Screenshots & andere Anlagen**

**Comment by PalmTamino** [comment]
Tatsächlich ist mir aufgefallen dass das nur manchmal so ist, meistens wird es bei mir in MSGs angezeigt.

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
