### ISSUE TITLE
Sammelthread: Endurion Nachrichten nicht konsistent

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#45]
<img width="659" alt="Screenshot 2021-08-16 101327" src="https://user-images.githubusercontent.com/36358673/129533208-2a1a9e48-753a-463b-90c6-b8588640d674.png">
<img width="491" alt="Screenshot 2021-08-16 101848" src="https://user-images.githubusercontent.com/36358673/129533211-ffdd0180-e295-4811-8a43-6640bd25d9cd.png">

**Comment by Whitescan** [comment]
> 
> 
> <img alt="Screenshot 2021-08-16 101327" width="659" src="https://user-images.githubusercontent.com/36358673/129533208-2a1a9e48-753a-463b-90c6-b8588640d674.png">
> 
> <img alt="Screenshot 2021-08-16 101848" width="491" src="https://user-images.githubusercontent.com/36358673/129533211-ffdd0180-e295-4811-8a43-6640bd25d9cd.png">

Behoben.

**Comment by PalmTamino** [comment]
> > <img alt="Screenshot 2021-08-16 101327" width="659" src="https://user-images.githubusercontent.com/36358673/129533208-2a1a9e48-753a-463b-90c6-b8588640d674.png">
> > <img alt="Screenshot 2021-08-16 101848" width="491" src="https://user-images.githubusercontent.com/36358673/129533211-ffdd0180-e295-4811-8a43-6640bd25d9cd.png">
> 
> Behoben.

Nein, nicht behoben.

**Comment by Whitescan** [comment]
Von @PalmTamino 
Generell
1. Nutze einen Befehl auf welchen du keinen Zugriff hast
2. Nutze einen Befehl den es nicht gibt
![131848049-c2ccf085-1b37-4d5f-8b3f-9032d3f61ed0](https://user-images.githubusercontent.com/70441126/132003241-fb3de098-7c28-43c4-ba71-64810d3f3657.png)

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
