### ISSUE TITLE
[OneBlock] Scoreboard geht nicht

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#46]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** OneBlock1 und Oneblock3

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 16.08.2021 - 18:55 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.** Es wird nurnoch die Sortierung im Scoreboard angezeigt.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu oneblock-1 oder oneblock-3
2. Siehe Fehler

**Comment by lxvin2** [comment]
https://prnt.sc/1ptjbce

**Comment by Whitescan** [comment]
Fehler nach einem Reload nicht mehr vorhanden. Fehlerquelle unbekannt.
