### ISSUE TITLE
[OneBlock 3 (Friendly) ] /auktionshaus befehl existiert nicht, das macht das Fkey menu useless, da sie den cmd nutzt.

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#47]
![image](https://user-images.githubusercontent.com/36358673/129942295-53ea7679-c367-4e0d-9ab4-b061fdf45b8f.png)

Der Befehl /auktionshaus existiert nicht, daher geht es auch nicht in der gui, einfach den Befehl in die AH config schreiben.

**Comment by PalmTamino** [comment]
Habe nicht genug Rechte diesen Fehler zu beheben, Boto konnte ihn bestätigen, jedoch haben wir keinen schnellen Fix gefunden.

**Comment by Whitescan** [comment]
Wird bei den nächsten Wartungen (heute) behoben.
