### ISSUE TITLE
[Boxed] Gekaufte Sachen aus dem AH erscheinen nicht im Inventar

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#48]
**Auf welchem Server hast du den Fehler gefunden?**
Boxed

**Wann hast du den Fehler gefunden? (Datum mit Uhrzeit)**
19.08.2021 17:05!

**Welche Minecraft Version nutzt du? (1.17.1)**
1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Taminator05

**Beschreibe den Fehler möglichst genau.**
Eigentlich sollte ich den Gegenstand erhalten, bin mir überhaupt nicht sicher woran es liegen könnte, dachte erst es liegt vielleicht am Vanish, habe es dann aber auch ohne getestet, mit dem gleichen Ergebnis. Ich hoffe das es nur bei mir so ist, sonst wäre das Fatal.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Hätte das gekaufte erhalten sollen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Ob2'
2. Nutze Befehl '/ah'
3. Klicke auf einen Gegenstand und Kaufe diesen
4. Ich erhielt ihn nicht, bin mir nicht sicher ob das Reproduzierbar ist '....'

**Screenshots & andere Anlagen**
Habe ein Video wo alles gezeigt wurde: https://streamable.com/g68l9c

**Comment by PalmTamino** [comment]
Das item ist unter Gekaufte Gegenstände, was ich nicht wusste.

**Comment by Whitescan** [comment]
Fehler nicht auf Oneblock sondern Boxed!

**Comment by PalmTamino** [comment]
> Fehler nicht auf Oneblock sondern Boxed!

Das was ich da reportet habe war nur ein Anwendefehler auf OneBlock. Das hat nichts mit dem Bug auf Boxed zu tun.

**Comment by PalmTamino** [comment]
Ich habe das Ah falsch bedient, daher schließe ich das issue jetzt.
