### ISSUE TITLE
[Hardcore] Pferde Bug

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#49]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** 
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 
19.08.2021 - ca. 22:30 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** 
Java 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen** 
Tifykillt

**Beschreibe den Fehler möglichst genau.** 
Wenn man am Hardcore Spawn mit ein Pferd kommt und dieses verlässt, wird man im Pferd angezeigt und man selbst kann durch die Weltgeschichte rumlaufen und für sich alles machen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Hardcore
2. Suche ein Pferd und geh zum Spawn
3. Versuch abzusteigen 
4. Siehe Fehler

**Comment by Whitescan** [comment]
Unter Beobachtung. Ursache bisher unklar.
