### ISSUE TITLE
[Generell] Vanish als Mod besser erkennen

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#50]
Um einfach die Leute besser zu sehen, ob sie im Vanish sind oder nicht, denn Befehl /modsee oder so (Natürlich nur nutzbar für Mods).

https://imgur.com/a/OF5fvU6

**Comment by PalmTamino** [comment]
Das wäre echt nice, fände aber auch noch cool, das wenn man im Vanish ist, das man dann mit schnellem doppeltem drücken der Shift-Taste in den Spectator kommt, und wieder zurück.

**Comment by lxvin2** [comment]
Also ein "Mod Zuschauermodus" wo das Inventar gespeichert wird, wenn man rein geht und dann die Mod Items kommen

**Comment by lxvin2** [comment]
Ich versuch es mal in Skript selber zu machen haha

**Comment by Whitescan** [comment]
Abgelehnt, ist nicht Zielführender Aufwand.
