### ISSUE TITLE
[Generell] Rotierende Minigames 

### ISSUE THREAD

**Issue by Jessi1Pingu** [EndurionNetwork/Endurion#51]
Minigames die alle zwei Wochen zum Beispiel abwechseln.
Mögliche Minigames:

-Outbreak
-BedWars
-SkyWars
-GetDown
-Kit PvP

Durch diese Abwechslung haben wir kein Outbreak mehr wo ein Geister Spielmodi ist, sondern eben alle paar Wochen für eine bestimmte Zeit da ist. 

-In den jeweiligen Spielmodi kann man auch dann Cosmetics verwenden.

**Comment by PalmTamino** [comment]
Würde mich dafür auch denke ich einbringen können, da ich die Server ja schon vorbereiten könnte, dann müsste sie whitescan nur online bringen, und im Teleporter ersetzen.

**Comment by Whitescan** [comment]
Teils angenommen. Über die Umsetzung muss noch diskutiert werden.
