### ISSUE TITLE
[Generell] ":" wird als kein Befehl anerkannt 

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#52]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** Überall 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 20.08.2021 - 16:16 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.** Wenn man bei /r mit : oder irgendein Emoji wie :c, :3, :/, :D, D:, :|

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf denn Server
2. Schreib jemanden mit einen Emoji zurück (Versuch es)
3. Sieh Fehler

**Comment by PalmTamino** [comment]
Kann ich bestätigen

**Comment by Whitescan** [comment]
Wird in den nächsten Wartungen (heute) behoben.
