### ISSUE TITLE
[Hardcore] /suicide befehl geht nicht 

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#53]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
20.08.2021 -- 20:30

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Taminator05

**Beschreibe den Fehler möglichst genau.**
/suicide geht nicht, eigentlich sollte man sterben, wenn man diesen Befehl ausführt.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Hardcore'
2. Nutze Befehl '/suicide'
4. Siehe Fehler 'Nicht der Befehl den du suchst'

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/36358673/130278203-48471265-1de2-443c-b5fa-8fad915558b3.png)

**Comment by Whitescan** [comment]
Es ist beabsichtigt das dieser Befehl nur auf Outbreak funktioniert. Kein Fehler.

**Comment by PalmTamino** [comment]
> 
> 
> Es ist beabsichtigt das dieser Befehl nur auf Outbreak funktioniert. Kein Fehler.

Vorschlag: Der Befehl wird auch nur auf OutBreak vorgeschlagen
