### ISSUE TITLE
[Hardcore] Lands Plugin auf deutsch stellen.

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#54]
![image](https://user-images.githubusercontent.com/36358673/130279719-e6b8a718-51ca-4548-87d6-d8126b817bf2.png)

Tatsächlich unterstützt es auch deutsch. Musst nichts übersetzen

**Comment by Whitescan** [comment]
Eigentlich soll es auf Deutsch sein, dies ist ein Fehler der zu beheben ist.

**Comment by Whitescan** [comment]
Behoben.
