### ISSUE TITLE
[OB1,2,3] Hologram, welches besagt das die Portale nicht gehen

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#55]
Hey, auf den Servern ist am Spawn noch dieses Hologram, welches sagt das die Portale nicht gehen, obwohl sie ja wieder gehen.
![grafik](https://user-images.githubusercontent.com/36358673/130320498-586292cb-4d5a-4e3c-a1c0-c33e970943e8.png)

**Comment by Blu3Crystal** [comment]
Ist entfernt.
