### ISSUE TITLE
[Hardcore] /fly wird bei Moderatoren direkt deaktiviert

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#59]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 23.08.2021 - 22:22 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)** Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.** /fly wird bei Moderatoren direkt deaktiviert

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Flug-Modus sollte an bleieben.

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf Hardcore
2. Nutze denn Befehl /fly
3. Siehe Fehler

**Screenshots & andere Anlagen**
![Screenshot_1](https://user-images.githubusercontent.com/88348034/130514243-fe5e407c-d92b-4b51-b9f5-74bd0194124f.png)

**Comment by PalmTamino** [comment]
Kann ich bestätigen, Fly geht nur auf eigenen Ländern in Hardcore.

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
