### ISSUE TITLE
[Hardcore] [Tablist] MVP an der falschen Stelle 

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#61]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
24.08.2021 -- 17:22

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Taminator05

**Beschreibe den Fehler möglichst genau.**
Warum ist ein MVP nicht unter dem Builder? Sondern mitten in den Spielern?

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Er müsste in der Tablist unter dem Builder sein.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Hardcore'
2. Hoffe dass 'Tifykillt' online ist
3. Halte die  'Tab' taste
4. Siehe Fehler 'Siehe wo Tifykillt in der Tabliste ist.'

**Screenshots & andere Anlagen**
![grafik](https://user-images.githubusercontent.com/36358673/130644601-17a3caa4-34ad-4ec0-a959-6708fd215525.png)

**Comment by Whitescan** [comment]
Die Tablist spinnt einfach manchmal. Bei Tifykillt habe ich ihm extra den Prefix gegeben, allerdings wird er nicht richtig sortiert.
