### ISSUE TITLE
[Hardcore] Vorschlag zu den Köpfen nach dem Tot

### ISSUE THREAD

**Issue by shiraito22** [EndurionNetwork/Endurion#62]
Aktuell ist es in Hardcore möglich, dass man bevor man sich ausloggt (und man weiß, das man für über 6Stunden nicht mehr online kommt), man sich einfach selbst umbringt und der Kopf in einen Trichter fällt,  sodass im Falle eines Kampfes ein Gildenmitglied einen einfach wiederbeleben kann. Allerdings wird an diesem Konzept kritisiert, dass es den "Hardcore" Aspekt aus dem Spielmodus rausnimmt. 

Mein Vorschlag wäre folgender:
Man könnte es so machen, dass nachdem man stirbt man 
1. sich nur noch mit dem "neusten" Kopf wiederbeleben kann 

  oder       
                                                              
 2. die Köpfe nur 30min nach dem Tot funktionieren und danach  nicht   mehr funktionieren und nur als Deko da sein können 

     
Dadurch wäre ein Kampf nun für mehr Spieler eine folgenreichere Entscheidung und ein Tot hätte nun einen größeren impact.

Vielen Dank für die Aufmerksamkeit,
mit freundlichen Grüßen shiraito

**Comment by Whitescan** [comment]
Angenommen. Wird mit hoher Priorität bearbeitet. @Whitescan

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
