### ISSUE TITLE
[Boxed] Border verschiebt sich falsch

### ISSUE THREAD

**Issue by Krescher15** [EndurionNetwork/Endurion#66]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**

Boxed

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**

Freitag, 27. August 2021    13:30

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**

Minecraft 1.16.5/Fabric (Modded)

**Nenne uns bitte deinen Minecraft Benutzernamen**

Kreescher15

**Beschreibe den Fehler möglichst genau.**

Wenn man im Nether (zumindestens ist es bis jetzt nur im Nether aufgetreten) seine Boxed versucht zu verschieben, kann es sein das man die Border verschiebt aber der Bereich in dem man agieren kann ändert sich nicht

**Wie hätte das Endergebnis stattdessen aussehen sollen?**

Die Border + der Bereich in dem man agieren kann sollten zusammen bewegt werden

**Schritte um den Fehler zu reproduzieren**
1. Nether gehen
2. Boxed verschieben

**Screenshots & andere Anlagen**

Fehler ist bei LauraDasBrot extrem aufgetreten (OneBlock 1)

**Comment by Whitescan** [comment]
Fehler live gesehen. Keine Erklärung für dieses Verhalten...
