### ISSUE TITLE
[Generell] Keine Rechte auf /clearchat mehr

### ISSUE THREAD

**Issue by NiAnLaster** [EndurionNetwork/Endurion#67]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Am 03.08.2021

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
NiAnLaster

**Beschreibe den Fehler möglichst genau.**
Man kann kein /cc -->/clearchat dort steht "Fehler! Das ist nicht der Befehl den du Suchst..."

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Chat hätte gereinigt sein sollen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Einem Modus'
2. Nutze Befehl '/cc'
3. Klicke auf '//'
4. Siehe Fehler "Fehler Das ist nicht der Befehl den du Suchst..."
 

**Screenshots & andere Anlagen**
//

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
