### ISSUE TITLE
[OneBlock 1,2,3 Boxed 1,2,3] /help Befehl sollte hilfe geben anstatt eines Berechtigungs fehlers.

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#69]
Beim eingeben des Befehls "/help" sollte es einen kleinen guide oder so etwas geben, anstatt eines Fehlers.

**Comment by PalmTamino** [comment]
Info: Endurion Spielmodis zeigen nach eingabe dieses Befehls die Plugins

**Comment by Whitescan** [comment]
Es gibt Tutorials am Spawn.

**Comment by PalmTamino** [comment]
> Es gibt Tutorials am Spawn.

Dann sollte man /help ganz ausbauen, aber auszugeben das man keine Rechte hat wäre in meinen Augen unprofessionell.
