### ISSUE TITLE
[Hardcore] Combat Logger TPA funktioniert

### ISSUE THREAD

**Issue by HerrDiebholz** [EndurionNetwork/Endurion#71]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore
**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
01.09.2021 22:30 Uhr
**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Optifine 1.16.5
**Nenne uns bitte deinen Minecraft Benutzernamen**
HerrDiebholz
**Beschreibe den Fehler möglichst genau.**
Spieler können während sie in einem Kampf sind TPA annehmen und versenden.
**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Die TPA hätte abgebrochen werden sollen.
**Schritte um den Fehler zu reproduzieren**
1. Gehe als Spieler zu Hardcore
2. Nutze Befehl /t[a im Kampf
3. Siehe Fehler

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
