### ISSUE TITLE
[Generell] Verschiedene Fehlernachrichten.

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#72]
Info: Dies ist nur ein Sehr kleiner Fehler, und er ist natürlich auf jedenfall nicht dringend zu beheben, dennoch wollte ich ihn hier mal auf GitHub stellen, da es ja immerhin ein kleiner Fehler ist^^

**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
02.09.2021 -- 14:57

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
Taminator05

**Beschreibe den Fehler möglichst genau.**
Bei der Eingabe eines Kommandos, auf welches ich keinen Zugriff habe in diesem Fallwar es jetzt "/pl" kommt die Nachricht Fehler! Das ist nicht der Befehl den du suchst, aber wenn ich etwas wie "/fjdksfjdsk" eingebe, dann kommt die Nachricht Fehler! Das ist nicht das Kommando das du suchst...

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Beide Nachrichten hätten gleich sein sollen

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf 'play.endurion.net'
2. Nutze einen Befehl auf welchen du keinen Zugriff hast
3. Nutze einen Befehl den es nicht gibt
4. Vergleiche Nachrichten '....'

**Screenshots & andere Anlagen**
![grafik](https://user-images.githubusercontent.com/36358673/131848049-c2ccf085-1b37-4d5f-8b3f-9032d3f61ed0.png)

**Comment by Whitescan** [comment]
Verschoben in Issue #45
