### ISSUE TITLE
[Discord] Mutes gehen nicht für Threads

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#73]
**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 02.09.2021 - 19:00 Uhr

**Nenne uns bitte deinen Discord Benutzernamen** 𝓵𝔁𝓿𝓲𝓷07#6783

**Beschreibe den Fehler möglichst genau.** Wenn man einen Discord Mute hat, kann man immernoch in Threads reinschreiben und somit sein Mute umgehen.

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Er sollte es nicht können,  da er gemutet war.

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf denn Discord Server
2. Mute einen
3. Der soll einmal ein Thread schreiben.
4. Siehe Fehler

**Screenshots & andere Anlagen**
https://prnt.sc/1r1wzi7
https://prnt.sc/1r1x0hl

**Comment by Mind0fBenni** [comment]
@Krescher15  wurde der fehler schon gelöst?

**Comment by Whitescan** [comment]
Vermutlich wurde in dem Bot das Feature Threads zum damaligen Zeitpunkt noch nicht behandelt.
Gehe davon aus das es nun passt. @Krescher15 ?

**Comment by Krescher15** [comment]
Ja, die Funktion Threads zu erstellen wurde eh im großen und Ganzen eingeschränkt.
Damit wurden dann auch die Rechte und die Bots konfiguriert.
