### ISSUE TITLE
[Vorschlag] "Dismiss Forever" für den Broadcast

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#75]
"/dismiss support_message" würde dann diesen Broadcast für mich blocken, dies ist cool für Spieler die hier schon lange spielen, und denen diese Meldung auch nicht mehr weiterhilft, da sie diese schon sehr oft gesehen haben.

**Comment by Whitescan** [comment]
Es gibt einen Bypass. Aber wir wollen die Spieler konstant daran erinnern. Es sind eben wichtige Erinnerungen die man nicht deaktivieren können soll.
