### ISSUE TITLE
[Oneblock] Man kann mit /lay in der Luft fliegen

### ISSUE THREAD

**Issue by snowwloop** [EndurionNetwork/Endurion#77]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Sonntag, 5. September 22:08 

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java - 1.17.1 (sollte aber in allen Versionen das selbe Problem sein)

**Nenne uns bitte deinen Minecraft Benutzernamen**
snowloop

**Beschreibe den Fehler möglichst genau.**
Wenn man irgendwie auf einem temporären Block /lay macht, schwebt man in der Luft auf dem Block weiter.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Der /lay Befehl sollte sich auflösen und man sollte fallen anstatt "in der Luft zu schweben"

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu Oneblock und stelle dich entweder auf eine Todeskiste (diesen gelten als Block und wenn sie "eingesammelt" werden, bleibt man weiterhin liegen, oder stelle dich in den Aufzug von Ice_Dream___ (wenn dieser fährt, entstehen Blöcke an einer Postion, gehen aber wieder weg.)
2. Nutze Befehl /lay
3. Siehe Fehler du solltest in der Luft liegen bleiben, ohne dass ein Block unter dir ist

**Screenshots & andere Anlagen**
[![2021-09-05_22](url) 00 16](https://user-images.githubusercontent.com/90156150/132140184-68d1eae2-afb1-4d3c-8c4f-ad54e70397f1.png)

**Comment by snowwloop** [comment]
Wenn man sich in dieser Lage zu einem Ob warp teleportiert, ist man für **sich selber** unsichtbar. Man darf ich dieser Zeit weder sprinten noch sneaken, da sonst der Bug "aufhört". Man kann sich jedoch weiterhin teleportieren und bleibt unsichtbar.

Die Karotte in der Mitte des Bildschirms bin ich :p 

![2021-09-05_22 22 32](https://user-images.githubusercontent.com/90156150/132140563-450a30bb-653f-46ae-93d3-fcef6e184ed2.png)
![2021-09-05_22 23 32](https://user-images.githubusercontent.com/90156150/132140564-c003d8ea-a49c-4bc3-9a6f-6f8935c346cc.png)
![2021-09-05_22 20 13](https://user-images.githubusercontent.com/90156150/132140566-237608c3-8e88-4a2b-a8d8-5cbdde61e014.png)

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
