### ISSUE TITLE
[Generell] Meldung "Entfernte 0 Entitäten" bei 0 - (z.B. 5) Entitäten nicht anzeigen

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#78]
![image](https://user-images.githubusercontent.com/36358673/132231011-189f59be-1639-4e10-9ccd-cc54e119f897.png)

Diese Meldung nur zeigen, wenn z.B. 5 Entitäten entfernt wurden.

**Comment by Whitescan** [comment]
Es wird ein clear angekündigt, keine Nachricht zu geben würde die Nutzer in "Angst" lassen.

**Comment by PalmTamino** [comment]
> Es wird ein clear angekündigt, keine Nachricht zu geben würde die Nutzer in "Angst" lassen.

Angst das 0 Entitäten gekillt werden? Dass ist schon ein Fehler. Die Nachricht 0 Entitäten wurden entfernt ist eben unlogisch.

**Comment by PalmTamino** [comment]
Muss ja nicht gleich ab 5, wenigstens ab 1 um den Fehler zu beheben.

**Comment by Whitescan** [comment]
Nein die Spieler bekommen einen clear angekündigt. Und wenn dann kein Feedback kommt denken sie etwas funktioniert nicht richtig. Kommt aber die Meldung das es stattgefunden hat und nichts entfernt werden musste: umso besser.
