### ISSUE TITLE
[Lobby] "Fliegen" unter der Höhe 0 möglich

### ISSUE THREAD

**Issue by snowwloop** [EndurionNetwork/Endurion#79]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
In der Lobby

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
7. September, 21:12

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.4 - Optifine

**Nenne uns bitte deinen Minecraft Benutzernamen**
snowloop 

**Beschreibe den Fehler möglichst genau.**
Unter Höhe 0 kann man unendlich oft doppelspringen, was dazu führt, dass man flieeegt. Ich weiß nicht, ob das den Server irgendwie stört, aber es ist halt ein Bug oder nicht? :p

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man sollte sich einmal durch Doppelspringen retten dürfen und dann ins Void fallen müssen 

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '/lobby'
2. Falle aus der Welt
3. Spamme deine Leertaste
4. FLIEGE

**Screenshots & andere Anlagen**
![2021-09-07_21 09 36](https://user-images.githubusercontent.com/90156150/132398966-e7e6263e-2549-482f-80b7-efacadfd1689.png)
![2021-09-07_21 09 50](https://user-images.githubusercontent.com/90156150/132398971-90bbf5c4-8e25-4321-a678-4e7f42ad9218.png)

**Comment by PalmTamino** [comment]
Kann ich bestätigen

**Comment by Whitescan** [comment]
Der #Entity.isOnGround() check von Minecraft ist echt ein Witz 💯 

Aber Spaß beiseite, es ist vermutlich nicht einfach diesen Fehler zu beheben. 
Hat aber auch geringe Priorität.
