### ISSUE TITLE
[Oneblock] Chat wird manchmal blockiert

### ISSUE THREAD

**Issue by Whitescan** [EndurionNetwork/Endurion#8]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock1

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
nicht bekannt.

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
HerrDiebholz

**Beschreibe den Fehler möglichst genau.**
Wenn ein Spieler in den Chat schreibt, kommt manchmal eine Fehlermeldung und die Nachricht wird nicht abgesendet. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Die Chatnachricht sollte gesendet werden.

**Schritte um den Fehler zu reproduzieren**
nicht bekannt. Fehler tritt sporadisch auf.

**Screenshots & andere Anlagen**
[Screenshot der Fehlermeldung](https://discord.com/channels/788319326120837160/856610678953607228/869708854563319808)

**Comment by Whitescan** [comment]
Es ist unklar unter welchen bedingungen dieser Fehler Auftritt. Weitere Informationen müssen gesammelt werden.

**Comment by Tigerhai1030** [comment]
![Bug](https://user-images.githubusercontent.com/88233099/127772399-fc9d9cb1-22d1-4b79-9a36-c500219b3374.PNG)
 Hatte das Problem auch schon öfters auf Oneblock2 (spiele nur auf diesen aktiv) 
 Fehlermeldung kommt zufällig, ohne grund bzw Vorwarnung
