### ISSUE TITLE
[OneBlock] Spawner anpassen

### ISSUE THREAD

**Issue by Blu3Crystal** [EndurionNetwork/Endurion#80]
Laut einem User gab es damals in PalmCraft "Blazes" für 150.000 zu kaufen.
Ich würde gern diesen Mob und eventuell noch andere einfügen.

Dies geht unter Upgradable Spawners an sich ja richtig einfach, der Preis würde dann natürlich auch bei 150.000 liegen.
Unter anderem würde ich gern die Mobs auch in unser /Shop System einführen, und nicht nur nachdem man einen Spawner gekauft hat.

So kostet zB eine Kuh nur 5000, da man es "umwandelt" im Spawner, ein Preis wie bei den anderen 16.500 wäre angemessener.
![Unbenannt](https://user-images.githubusercontent.com/88382159/132897348-ffbe681f-83ea-48cf-b19c-cf3f93f65220.PNG)
![Unbenannt](https://user-images.githubusercontent.com/88382159/132897410-a04ab0b4-f0a6-465f-a910-cd3fcbf8ea72.PNG)

**Comment by PalmTamino** [comment]
Nicht so einfach möglich da wir jetzt das Shopsystem von @Whitescan nutzen, welches soweit ich weiß keine untersützung für Custom Items wie upgradeable spawners bietet.
