### ISSUE TITLE
[Lobby] Scoreboard anpassen

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#81]
![grafik](https://user-images.githubusercontent.com/36358673/133274136-78f75f83-cf9e-4827-9ffb-22f1defa60db.png)

1: Warum werden in dem Scoreboard Gems und Coins schon seit release angezeigt, obwohl beides nicht erhältlich ist.
2: Warum steht da so einfach random der Rang, würde vorschlagen das da Rang (neue Zeile) "Techniker" steht. Beides natürlich in Dick, da es sonst nicht passen würde.
3: Warum gibt es überhaupt dieses ScoreBoard? Seinen Rang weiß man ja, und den Namen auch, und die Coins und Gems sind ja eh nicht erhältlich.

Mein Vorschlag: Am liebsten das Scoreboard entfernen (3) oder nur die Sache mit (2) ändern

**Comment by Whitescan** [comment]
Das Scoreboard ist Fehlerhaft.

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
