### ISSUE TITLE
[Generell] Vor allen von Spielern geschriebenen Nachrichten befindet sich ein Leerzeichen

### ISSUE THREAD

**Issue by PalmTamino** [EndurionNetwork/Endurion#82]
![grafik](https://user-images.githubusercontent.com/36358673/133275610-c9444655-92a5-46de-961d-af07c9086da8.png)

Vergleich mit dem Info text.

**Comment by Whitescan** [comment]
Kein Fehler. Dies geschieht mit generell allen Spielernachrichten und ist dazu da um es von Systemnachrichten hervorzuheben.
