### ISSUE TITLE
[Generell] Rechtschreibfehler beim Tempban

### ISSUE THREAD

**Issue by Blu3Crystal** [EndurionNetwork/Endurion#83]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
Ist unwichtig

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
Blu3_Crystal

**Beschreibe den Fehler möglichst genau.**
Rechtschreibfehler beim tempbannen.
"tempor"

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
"temporär"

**Schritte um den Fehler zu reproduzieren**
---

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/88382159/133510393-6831bb57-231f-4782-8f5a-32ffd9e4d6ee.png)

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
