### ISSUE TITLE
[OneBlock] Quickshop funktioniert nicht

### ISSUE THREAD

**Issue by Blu3Crystal** [EndurionNetwork/Endurion#84]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
OneBlock 1-3

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
16.09.2021 - 15:15

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
Blu3_Crystal - erneut getestet von Kachiofen und dem User ImmaBeBad

**Beschreibe den Fehler möglichst genau.**
Man kann sich keinen Quickshop mit den Truhensystem erstellen.
Befehl wird nicht ausgeführt. (Keine Fehlermeldung)

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Truhenshop mit Item und Schild.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu OneBlock
2. Klicke auf eine Truhe mit den Item welches du verkaufen möchtest.
3. Siehe Fehler, Shop wird nicht erstellt.
4. Mit dem Befehl /quickshop erscheint folgende Fehlermeldung

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/88382159/133619910-25f8cfa6-c497-47b2-9b1d-c96914bb9a0c.png)

**Comment by Whitescan** [comment]
Behoben in den letzten Wartungen.
