### ISSUE TITLE
[Überall] Moderatoren können nicht mit Farbcodes schreiben.

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#85]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
 Überall getestet

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 
17.09.2021 - 16:24 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
 Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
 lxvin07

**Beschreibe den Fehler möglichst genau.** 
Moderatoren können nicht mehr mit Farbcodes im Chat schreiben.

**Wie hätte das Endergebnis stattdessen aussehen sollen?** 
Farbcodes sollten gehen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf Endurion
2. Versuche mit Farbcodes was zu schreiben.

**Screenshots & andere Anlagen**
https://prnt.sc/1skmwnm

**Comment by Whitescan** [comment]
Schreibfehler im Code (ChatHandler) gefunden. Temporäre Rechte hinzugefügt. 
Wird mit den nächsten Wartungen entgültig behoben.
