### ISSUE TITLE
[OneBlock (1)] Shop nicht verfügbar

### ISSUE THREAD

**Issue by faulerkakao** [EndurionNetwork/Endurion#87]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)
-Oneblock**

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)
-ca 11Uhr**

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)
-Minecraft 1.16.4**

**Nenne uns bitte deinen Minecraft Benutzernamen
-fauler_kakao**

**Beschreibe den Fehler möglichst genau.
-wenn man /shop eintippt kommt eine Fehlermeldung**

**Wie hätte das Endergebnis stattdessen aussehen sollen?
-die Shop GUI hätte sich öffnen sollen**

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'oneblock 1'
2. Nutze Befehl '/shop'
3. Siehe Fehler 'sehe Bild anhang'

Screenshots & andere Anlagen
![Fehler](https://user-images.githubusercontent.com/91077725/134162755-933f573e-b6b5-403d-a440-d8e3b0938622.png)

**Comment by lxvin2** [comment]
Bestätige. Auf keinen Server geht der /Shop Befehl mehr.
https://prnt.sc/1t3g6dm

**Comment by Whitescan** [comment]
Duplikat von #84

**Comment by Whitescan** [comment]
Wurde mit den letzten Wartungen behoben.
