### ISSUE TITLE
[Oneblock] kein /quest

### ISSUE THREAD

**Issue by faulerkakao** [EndurionNetwork/Endurion#89]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
-Oneblock

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
-ca. 11:30

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
-16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
-fauler_kakao

**Beschreibe den Fehler möglichst genau.**
-bei /quest kommt eine Fehlermeldung

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
-die Quest GUI hätte ich öffnen sollen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'oneblock 1'
2. Nutze Befehl '/quest'
3. Siehe Fehler 'sehe Anhang'

**Screenshots & andere Anlagen*
![fehler2](https://user-images.githubusercontent.com/91077725/134489250-5f03778a-fe4f-4da7-ae74-2de127c8bbe2.png)
*

**Comment by lxvin2** [comment]
Bestätige

**Comment by Blu3Crystal** [comment]
Wir haben ein neues Quest System ohne GUI, da das alte nicht mehr unterstützt wird.

Hier muss man mit Commands arbeiten, diese werde ich noch als Holograms besser erklären.

Bsp.
/quests list
/quests take Iron Miner
Im Chat "yes" schreiben -> Siehe Anforderungen welche du benötigst um die Quest zu starten.
