### ISSUE TITLE
[OneBlock1-3, Boxed1-3] /money fehler

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#90]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)** 
OneBlock1-3, Boxed1-3

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
irrelevant

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
irrelevant

**Nenne uns bitte deinen Minecraft Benutzernamen** 
lxvin07

**Beschreibe den Fehler möglichst genau.** Bei /money werden die Farbcodes angezeigt und nicht verbraucht.

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Die Farbcodes sollten gehen

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf OneBlock
2. Nutze /money
3. siehe Fehler

**Screenshots & andere Anlagen**
https://prnt.sc/1tc0njw

**Comment by lxvin2** [comment]
Es sind generell die Nachrichten, die ein Essentials gibt.

**Comment by Blu3Crystal** [comment]
Codefehler in der Essentials properties Datei.
Wurde auf jeden OneBlock nun gefixt.
