### ISSUE TITLE
[OneBlock(1)] Man bekommt das Geld von Usershop Verkäufen nicht

### ISSUE THREAD

**Issue by einsCoco** [EndurionNetwork/Endurion#91]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock 1

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
23.9.2021
20:00 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
FireHD_Lukas

**Beschreibe den Fehler möglichst genau.**
Wenn man im Shop für grössere Mengen an Geld etwas kauft bekommt es der Spieler erst nach paar Tagen. Bei kleineren Summen bekommt man das Geld direkt

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Das er das ganze Geld bekommen sollte

**Schritte um den Fehler zu reproduzieren**
1. Gehe zum Shop
2. Klicke auf die Kiste
3. Setze Elytren im Wert von 52k in den Shop 
4. Verkaufe diese in grossen Mengen (4 Stück)
5. Der Fehler ist dass man das Geld nicht bekommt

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Bitte befolge die Vorlage. Mit diesen Informationen kann ich nicht arbeiten.

**Comment by Whitescan** [comment]
Hallo @einsCoco ,
hier fehlt Titel, Nachweise und Schritte um den Fehler zu reproduzieren. 
Bitte dringend angeben. (z.B. was verkauft / gekauft wurde und für wie viel Geld)
