### ISSUE TITLE
[Generell] Quest "Iron Miner" Funktioniert nicht

### ISSUE THREAD

**Issue by Kachiofen** [EndurionNetwork/Endurion#92]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
24.09.2021 15:00

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
LabyMod 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
Kachiofen

**Beschreibe den Fehler möglichst genau.**
Will man die Quest "Iron Miner" starten wird verlangt eine Steinspitzhacke zu besitzen, jedoch wird ein Fehler ausgegeben obwohl man eine Steinspitzhacke hat. Es würde sich hier auch anbieten es zu erlauben auch eine Eisen-,Diamant- oder Netheritespitzhacke als Möglichkeit zu geben.
Es ist auch die Übersetzung auf Deutsch nur teilweise vorhanden

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Irgend einen Modus'
2. Nutze Befehl  '/quests take Iron Miner' und 'Yes'
4. Siehe Fehlermeldung 'You must have a Stonepickaxe first'

**Screenshots & andere Anlagen**
![2021-09-24_16 45 52](https://user-images.githubusercontent.com/87825743/134696082-b79149ce-704f-4af4-b887-dc99a799dfde.png)

**Comment by Whitescan** [comment]
Quest System wurde geändert.
