### ISSUE TITLE
Oneblock 1

### ISSUE THREAD

**Issue by einsCoco** [EndurionNetwork/Endurion#93]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**

**Nenne uns bitte deinen Minecraft Benutzernamen**

**Beschreibe den Fehler möglichst genau.**

**Wie hätte das Endergebnis stattdessen aussehen sollen?**

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by PalmTamino** [comment]
Zu wenig informationen.
