### ISSUE TITLE
Oneblock1 

### ISSUE THREAD

**Issue by einsCoco** [EndurionNetwork/Endurion#94]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Oneblock 1

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
23.9.2021
20:00 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
FireHD_Lukas

**Beschreibe den Fehler möglichst genau.**
Wenn jemand bei ihm für grössere Summen eingekauft hat, hat er das Geld nicht bekommen und musste "Steuern" zahlen.
Bei kleineren Summen bekam er das Geld.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Das er das ganze Geld bekommen sollte

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Dublikat zu #91
