### ISSUE TITLE
Hardcore

### ISSUE THREAD

**Issue by einsCoco** [EndurionNetwork/Endurion#95]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hardcore

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
27.9.2021 20:15 Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
Java 1.16.1

**Nenne uns bitte deinen Minecraft Benutzernamen**
CommanderTaha27

**Beschreibe den Fehler möglichst genau.**
Die Villiger nehmen keinen anderen Job an und behalten ihren alten.

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Das die den anderen Job annehmen

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Das liegt leider nicht an uns. 
Erstmal ist klarzustellen das es "Arbeitsfaule" Dorfbewohner gibt, die einfach keinen Job annehmen.

Das Verhalten (die KI) der Dorfbewohner wird von uns als Server nicht geändert.
Lediglich das Spawnen von Dorfbewohnern wird verhindert. Nicht das wechseln des Jobs.
