### ISSUE TITLE
[Generell] Discord Link geht nicht

### ISSUE THREAD

**Issue by lxvin2** [EndurionNetwork/Endurion#96]
**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)** 02.10.2021 - 12:34 Uhr

**Nenne uns bitte deinen Minecraft Benutzernamen** lxvin07

**Beschreibe den Fehler möglichst genau.** Wenn du auf denn Link gehst, steht da nur: Einladung ungültig 

**Wie hätte das Endergebnis stattdessen aussehen sollen?** Weiterleitung zu Discord

**Schritte um den Fehler zu reproduzieren**
1. Gehe auf Endurion
2. Nutze Befehl /discord
3. Öffne denn Link

**Screenshots & andere Anlagen** https://prnt.sc/1uh9pwp

**Comment by Whitescan** [comment]
Boosts sind abgelaufen... discord.endurion.net geht weiterhin.

**Comment by Whitescan** [comment]
@Blu3Crystal kannst ja mal versuchen das mit @Jessi1Pingu zusammen zu beheben. 
Gibt bestimmt mehrere Stellen mit falschem Link.
