### ISSUE TITLE
[Boxed] Example Quest 5 nicht machbar

### ISSUE THREAD

**Issue by LuxorIjuri** [EndurionNetwork/Endurion#98]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Boxed 2 

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
06.10.2021

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.16.5

**Nenne uns bitte deinen Minecraft Benutzernamen**
LuxorTV 
Spieler der den Bug gefunden hat: Ara144HD
**Beschreibe den Fehler möglichst genau.**
Nach abschleißen der vierten Quest kann man die fünfte nicht machen dort steht: No Permission.  You don't have the
Permission for this Quest

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man hätte die Quest anfangen können sollen.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Boxed'
2. Nutze Befehl 'F um das menü zu öffnen.'
3. Klicke auf 'Quests->Example Quests-> Example Quest V'
4. Siehe Fehler 'Da steht: No Permission.  You don't have the
Permission for this Quest'

**Screenshots & andere Anlagen**

**Comment by PalmTamino** [comment]
Fehler behoben!
